---
- name: "End play if distribution not suported"
  meta: end_host
  when:
    - ansible_distribution != "Debian"
    - ansible_distribution != "Ubuntu"
    - ansible_distribution != "CentOS"

- name: "Check for oxidized_exporter binary"
  stat:
    path: '{{ oxidized_exporter_install_dir }}/oxidized-exporter'
  changed_when: false
  register: oxidized_exporter_install

- when: not oxidized_exporter_install.stat.exists or oxidized_exporter_force_install|bool
  block:
    - name: "Install requierements"
      package:
        name: '{{ oxidized_packages }}'
        state: present

- name: "Copy oxidized-exporter script"
  template:
    src: 'oxidized-exporter.j2'
    dest: '{{ oxidized_exporter_install_dir }}/oxidized-exporter'
    mode: '0755'
  notify: "restart oxidized_exporter"

- name: "Create systemd for oxidized_exporter"
  template:
    src: 'oxidized_exporter.service.j2'
    dest: '/etc/systemd/system/oxidized_exporter.service'
    mode: '0640'
  notify: "restart oxidized_exporter"

- name: "Enable and Start oxidized_exporter.service"
  systemd:
    name: oxidized_exporter
    state: started
    enabled: true
    daemon_reload: true
