---
- name: "Check for oxidized_exporter binary"
  stat:
    path: "/usr/local/bin/oxidized_exporter"
  changed_when: false
  register: oxidized_exporter_install

- when: not oxidized_exporter_install.stat.exists
  block:
    - name: "Install requierements"
      package:
        name: ["python3-requests", "python3-prometheus-client"]
        state: present

- name: "Copy oxidized_exporter script"
  template:
    src: oxidized_exporter.j2
    dest: /usr/local/bin/oxidized_exporter
    mode: '0755'
  notify: "restart oxidized_exporter"

- name: "Create systemd for oxidized_exporter"
  template:
    src: oxidized_exporter.service
    dest: /etc/systemd/system/
    mode: '0644'
  notify: "restart oxidized_exporter"

- name: "Enable and Start oxidized_exporter.service"
  systemd:
    name: oxidized_exporter
    state: started
    enabled: true
    daemon_reload: true
